import { phetsarath } from '@/styles/fonts';
import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        abel: ['var(--font-abel)'],
        adamina: ['var(--font-adamina)'],
        pirata_one: ['var(--font-pirata-one)'],
        gill_sans: ['var(--font-gill-sans)'],
        inandan: ['var(--font-inandan)'],
        phetsarath: ['var(--font-phetsarath)'],
      },
      backgroundImage: {
        'gradient-light-violet': 'linear-gradient(120deg, rgb(var(--color-violet) /100%), rgb(var(--color-light-violet) / 80%), rgb(var(--color-light-violet) / 60%))',
        'custom-gradient-15%': 'linear-gradient(to right, rgb(111,97,192) 15%, transparent)',
        'custom-gradient-45%': 'linear-gradient(to right, rgb(111,97,192) 45%, rgba(111,97,192,0.93) 53%, rgba(111,97,192,0.85) 60%, rgba(111,97,192,0.7) 70%, transparent)',
      },
      animation: {
        slideDown: 'slideDown 0.3s ease-in-out',
        slideUp: 'slideUp 0.3s ease-in-out',
        slideRight: 'slideRight 0.3s ease-in-out',
        slideLeft: 'slideLeft 0.3s ease-in-out',
      },
      keyframes: {
        slideDown: {
          '0%': { maxHeight: '0', opacity: '0' },
          '5%': { maxHeight: '50px', opacity: '0.05' },
          '10%': { maxHeight: '100px', opacity: '0.1' },
          '15%': { maxHeight: '150px', opacity: '0.15' },
          '20%': { maxHeight: '200px', opacity: '0.2' },
          '25%': { maxHeight: '250px', opacity: '0.25' },
          '30%': { maxHeight: '300px', opacity: '0.3' },
          '35%': { maxHeight: '350px', opacity: '0.35' },
          '40%': { maxHeight: '400px', opacity: '0.4' },
          '45%': { maxHeight: '450px', opacity: '0.45' },
          '50%': { maxHeight: '500px', opacity: '0.5' },
          '55%': { maxHeight: '550px', opacity: '0.55' },
          '60%': { maxHeight: '600px', opacity: '0.6' },
          '65%': { maxHeight: '650px', opacity: '0.65' },
          '70%': { maxHeight: '700px', opacity: '0.7' },
          '75%': { maxHeight: '750px', opacity: '0.75' },
          '80%': { maxHeight: '800px', opacity: '0.8' },
          '85%': { maxHeight: '850px', opacity: '0.85' },
          '90%': { maxHeight: '900px', opacity: '0.9' },
          '95%': { maxHeight: '950px', opacity: '0.95' },
          '100%': { maxHeight: '1000px', opacity: '1' },
        },
        slideUp: {
          '0%': { maxHeight: '1000px', opacity: '1' },
          '5%': { maxHeight: '950px', opacity: '0.95' },
          '10%': { maxHeight: '900px', opacity: '0.9' },
          '15%': { maxHeight: '850px', opacity: '0.85' },
          '20%': { maxHeight: '800px', opacity: '0.8' },
          '25%': { maxHeight: '750px', opacity: '0.75' },
          '30%': { maxHeight: '700px', opacity: '0.7' },
          '35%': { maxHeight: '650px', opacity: '0.65' },
          '40%': { maxHeight: '600px', opacity: '0.6' },
          '45%': { maxHeight: '550px', opacity: '0.55' },
          '50%': { maxHeight: '500px', opacity: '0.5' },
          '55%': { maxHeight: '450px', opacity: '0.45' },
          '60%': { maxHeight: '400px', opacity: '0.4' },
          '65%': { maxHeight: '350px', opacity: '0.35' },
          '70%': { maxHeight: '300px', opacity: '0.3' },
          '75%': { maxHeight: '250px', opacity: '0.25' },
          '80%': { maxHeight: '200px', opacity: '0.2' },
          '85%': { maxHeight: '150px', opacity: '0.15' },
          '90%': { maxHeight: '100px', opacity: '0.1' },
          '95%': { maxHeight: '50px', opacity: '0.05' },
          '100%': { maxHeight: '0', opacity: '0' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '5%': { transform: 'translateX(-95%)', opacity: '0.05' },
          '10%': { transform: 'translateX(-90%)', opacity: '0.1' },
          '15%': { transform: 'translateX(-85%)', opacity: '0.15' },
          '20%': { transform: 'translateX(-80%)', opacity: '0.2' },
          '25%': { transform: 'translateX(-75%)', opacity: '0.25' },
          '30%': { transform: 'translateX(-70%)', opacity: '0.3' },
          '35%': { transform: 'translateX(-65%)', opacity: '0.35' },
          '40%': { transform: 'translateX(-60%)', opacity: '0.4' },
          '45%': { transform: 'translateX(-55%)', opacity: '0.45' },
          '50%': { transform: 'translateX(-50%)', opacity: '0.5' },
          '55%': { transform: 'translateX(-45%)', opacity: '0.55' },
          '60%': { transform: 'translateX(-40%)', opacity: '0.6' },
          '65%': { transform: 'translateX(-35%)', opacity: '0.65' },
          '70%': { transform: 'translateX(-30%)', opacity: '0.7' },
          '75%': { transform: 'translateX(-25%)', opacity: '0.75' },
          '80%': { transform: 'translateX(-20%)', opacity: '0.8' },
          '85%': { transform: 'translateX(-15%)', opacity: '0.85' },
          '90%': { transform: 'translateX(-10%)', opacity: '0.9' },
          '95%': { transform: 'translateX(-5%)', opacity: '0.95' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        
      },
      
      
    },
    colors: {
      'dark-violet': 'rgb(var(--color-dark-violet) / <alpha-value>)',
      violet: 'rgb(var(--color-violet) / <alpha-value>)',
      'light-violet': 'rgb(var(--color-light-violet) / <alpha-value>)',
      purple: 'rgb(var(--color-purple) / <alpha-value>)',
      green: 'rgb(var(--color-green) / <alpha-value>)',
      red: 'rgb(var(--color-red) / <alpha-value>)',
      orange: 'rgb(var(--color-orange) / <alpha-value>)',
      'yellow-orange': 'rgb(var(--color-yellow-orange) / <alpha-value>)',
      yellow: 'rgb(var(--color-yellow) / <alpha-value>)',
      gray: 'rgb(var(--color-gray) / <alpha-value>)',
      white: 'rgb(var(--color-white) / <alpha-value>)',
    },
    screens: {
      xsm: '0px',
      sm: '576px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
      '2xl': '1400px',
    },
  },
  plugins: [],
} satisfies Config;
export default config;
